# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'game_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from ui.mylogwindow import MyLogWindow


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(807, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        numAgents = 2
        self.Logs = []
        for x in range(0, numAgents):
            self.Logs.insert(x, MyLogWindow(self.centralwidget))
            self.Logs[x].setGeometry(QtCore.QRect(x * 100 + 5, 330, 95, 161))
            self.Logs[x].setReadOnly(True)
            self.Logs[x].setObjectName("Agent" + str(x+1) + "Log")
        #self.Agent1Log = MyLogWindow(self.centralwidget)
        #self.Agent1Log.setGeometry(QtCore.QRect(50, 330, 171, 161))
        #self.Agent1Log.setReadOnly(True)
        #self.Agent1Log.setObjectName("Agent1Log")
        print(self.Logs)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 807, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))

    def moreText(self, MainWindow, text):
        for x in range(0, len(self.Logs)):
            self.Logs[x].append_message(text)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    first_window = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(first_window)
    first_window.show()
    for x in range(0, 50):
        ui.moreText(first_window, "Teste " + str(x))
    sys.exit(app.exec())
