class villageUI:

    def __init__(self):
        self.VillageName = ""
        # self.VillageName.setGeometry(QtCore.QRect(w + 175, 5, 50, 15))
        # self.VillageName.setAlignment(QtCore.Qt.AlignCenter)
        # self.VillageName.setObjectName("VillageName")
        # self.VillageType = QtWidgets.QLabel(self.centralwidget)
        # self.VillageType.setGeometry(QtCore.QRect(w + 175, 20, 50, 15))
        # self.VillageType.setObjectName("VillageType")
        # self.HealthBar = QtWidgets.QProgressBar(self.centralwidget)
        # self.HealthBar.setGeometry(QtCore.QRect(w + 5, 38, 390, 20))
        # self.HealthBar.setFont(font)
        # self.HealthBar.setLayoutDirection(QtCore.Qt.LeftToRight)
        # self.HealthBar.setAutoFillBackground(False)
        # self.HealthBar.setProperty("value", 100)
        # self.HealthBar.setTextVisible(True)
        # self.HealthBar.setInvertedAppearance(False)
        # self.HealthBar.setObjectName("HealthBar")
        # self.BarracksIcon = QtWidgets.QLabel(self.centralwidget)
        # self.BarracksIcon.setGeometry(QtCore.QRect(w + 10, 85, 35, 35))
        # self.BarracksIcon.setText("")
        # self.BarracksIcon.setPixmap(QtGui.QPixmap("ui_icons/Fort_%28Civ6%29.png"))
        # self.BarracksIcon.setScaledContents(True)
        # self.BarracksIcon.setAlignment(QtCore.Qt.AlignCenter)
        # self.BarracksIcon.setObjectName("BarracksIcon")
        # self.BuldingLevel = QtWidgets.QLabel(self.centralwidget)
        # self.BuldingLevel.setGeometry(QtCore.QRect(w + 170, 65, 60, 15))
        # self.BuldingLevel.setObjectName("BuldingLevel")
        # self.BuldingNextLevel = QtWidgets.QLabel(self.centralwidget)
        # self.BuldingNextLevel.setGeometry(QtCore.QRect(w + 280, 65, 60, 15))
        # self.BuldingNextLevel.setObjectName("BuldingNextLevel")
        # self.Barracks = QtWidgets.QLabel(self.centralwidget)
        # self.Barracks.setGeometry(QtCore.QRect(w + 70, 95, 60, 15))
        # self.villages[i].Barracks.setObjectName("Barracks")
        # self.BarracksLevel = QtWidgets.QLabel(self.centralwidget)
        # self.BarracksLevel.setGeometry(QtCore.QRect(w + 170, 95, 60, 15))
        # self.BarracksLevel.setObjectName("BarracksLevel")
        # self.BarracksNextLevel = QtWidgets.QLabel(self.centralwidget)
        # self.BarracksNextLevel.setGeometry(QtCore.QRect(w + 280, 95, 75, 15))
        # self.BarracksNextLevel.setObjectName("BarracksNextLevel")
        # self.FarmIcon = QtWidgets.QLabel(self.centralwidget)
        # self.FarmIcon.setGeometry(QtCore.QRect(w + 10, 120, 35, 35))
        # self.FarmIcon.setText("")
        # self.FarmIcon.setPixmap(QtGui.QPixmap("ui_icons/Farm_%28Civ6%29.png"))
        # self.FarmIcon.setScaledContents(True)
        # self.FarmIcon.setObjectName("FarmIcon")
        # self.Farm = QtWidgets.QLabel(self.centralwidget)
        # self.Farm.setGeometry(QtCore.QRect(w + 70, 130, 60, 15))
        # self.Farm.setObjectName("Farm")
        # self.FarmLevel = QtWidgets.QLabel(self.centralwidget)
        # self.FarmLevel.setGeometry(QtCore.QRect(w + 170, 130, 60, 15))
        # self.FarmLevel.setObjectName("FarmLevel")
        # self.FarmNextLevel = QtWidgets.QLabel(self.centralwidget)
        # self.FarmNextLevel.setGeometry(QtCore.QRect(w + 280, 130, 75, 15))
        # self.FarmNextLevel.setObjectName("FarmNextLevel")
        # self.MineIcon = QtWidgets.QLabel(self.centralwidget)
        # self.MineIcon.setGeometry(QtCore.QRect(w + 10, 155, 35, 35))
        # self.MineIcon.setText("")
        # self.MineIcon.setPixmap(QtGui.QPixmap("ui_icons/Mine_%28Civ6%29.png"))
        # self.MineIcon.setScaledContents(True)
        # self.MineIcon.setObjectName("MineIcon")
        # self.Mine = QtWidgets.QLabel(self.centralwidget)
        # self.Mine.setGeometry(QtCore.QRect(w + 70, 165, 60, 15))
        # self.Mine.setObjectName("Mine")
        # self.MineLevel = QtWidgets.QLabel(self.centralwidget)
        # self.MineLevel.setGeometry(QtCore.QRect(w + 170, 165, 60, 15))
        # self.MineLevel.setObjectName("MineLevel")
        # self.MineNextLevel = QtWidgets.QLabel(self.centralwidget)
        # self.MineNextLevel.setGeometry(QtCore.QRect(w + 280, 165, 75, 15))
        # self.MineNextLevel.setObjectName("MineNextLevel")
        # self.Iron = QtWidgets.QLabel(self.centralwidget)
        # self.Iron.setGeometry(QtCore.QRect(w + 50, 350, 60, 15))
        # self.Iron.setAlignment(QtCore.Qt.AlignCenter)
        # self.Iron.setObjectName("Iron")
        # self.IronValue = QtWidgets.QLabel(self.centralwidget)
        # self.IronValue.setGeometry(QtCore.QRect(w + 50, 380, 60, 15))
        # self.IronValue.setAlignment(QtCore.Qt.AlignCenter)
        # self.IronValue.setObjectName("IronValue")
        # self.Stone = QtWidgets.QLabel(self.centralwidget)
        # self.Stone.setGeometry(QtCore.QRect(w + 170, 350, 60, 15))
        # self.Stone.setAlignment(QtCore.Qt.AlignCenter)
        # self.Stone.setObjectName("Stone")
        # self.StoneValue = QtWidgets.QLabel(self.centralwidget)
        # self.StoneValue.setGeometry(QtCore.QRect(w + 170, 380, 60, 15))
        # self.StoneValue.setAlignment(QtCore.Qt.AlignCenter)
        # self.StoneValue.setObjectName("StoneValue")
        # self.Wood = QtWidgets.QLabel(self.centralwidget)
        # self.Wood.setGeometry(QtCore.QRect(w + 290, 350, 60, 15))
        # self.Wood.setAlignment(QtCore.Qt.AlignCenter)
        # self.Wood.setObjectName("Wood")
        # self.WoodValue = QtWidgets.QLabel(self.centralwidget)
        # self.WoodValue.setGeometry(QtCore.QRect(w + 290, 380, 60, 15))
        # self.villages[i].WoodValue.setAlignment(QtCore.Qt.AlignCenter)
        # self.WoodValue.setObjectName("WoodValue")
        # self.Army = QtWidgets.QLabel(self.centralwidget)
        # self.Army.setGeometry(QtCore.QRect(w + 90, 450, 60, 15))
        # self.Army.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        # self.Army.setObjectName("Army")
        # self.Warriors = QtWidgets.QLabel(self.centralwidget)
        # self.Warriors.setGeometry(QtCore.QRect(w + 90, 480, 60, 15))
        # self.Warriors.setObjectName("Warriors")
        # self.Archers = QtWidgets.QLabel(self.centralwidget)
        # self.Archers.setGeometry(QtCore.QRect(w + 90, 515, 60, 15))
        # self.Archers.setObjectName("Archers")
        # self.Catapults = QtWidgets.QLabel(self.centralwidget)
        # self.Catapults.setGeometry(QtCore.QRect(w + 90, 550, 60, 15))
        # self.Catapults.setObjectName("Catapults")
        # self.Cavalrymen = QtWidgets.QLabel(self.centralwidget)
        # self.Cavalrymen.setGeometry(QtCore.QRect(w + 90, 585, 60, 15))
        # self.Cavalrymen.setObjectName("Cavalrymen")
        # self.TotalArmy = QtWidgets.QLabel(self.centralwidget)
        # self.TotalArmy.setGeometry(QtCore.QRect(w + 90, 620, 60, 15))
        # self.TotalArmy.setObjectName("TotalArmy")
        # self.NumSoldiers = QtWidgets.QLabel(self.centralwidget)
        # self.NumSoldiers.setGeometry(QtCore.QRect(w + 170, 450, 60, 15))
        # self.NumSoldiers.setObjectName("NumSoldiers")
        # self.Offensive = QtWidgets.QLabel(self.centralwidget)
        # self.Offensive.setGeometry(QtCore.QRect(w + 240, 450, 60, 15))
        # self.Offensive.setObjectName("Offensive")
        # self.Defensive = QtWidgets.QLabel(self.centralwidget)
        # self.Defensive.setGeometry(QtCore.QRect(w + 320, 450, 60, 15))
        # self.Defensive.setObjectName("Defensive")
        # self.Log = QtWidgets.QTextBrowser(self.centralwidget)
        # self.Log.setGeometry(QtCore.QRect(w + 5, 650, 390, 130))
        # self.Log.setObjectName("Log")
        # self.WarriorsNum = QtWidgets.QLabel(self.centralwidget)
        # self.WarriorsNum.setGeometry(QtCore.QRect(w + 170, 480, 60, 15))
        # self.WarriorsNum.setObjectName("WarriorsNum")
        # self.ArchersNum = QtWidgets.QLabel(self.centralwidget)
        # self.ArchersNum.setGeometry(QtCore.QRect(w + 170, 515, 60, 15))
        # self.ArchersNum.setObjectName("ArchersNum")
        # self.CatapultsNum = QtWidgets.QLabel(self.centralwidget)
        # self.CatapultsNum.setGeometry(QtCore.QRect(w + 170, 550, 60, 15))
        # self.CatapultsNum.setObjectName("CatapultsNum")
        # self.CavalrymenNum = QtWidgets.QLabel(self.centralwidget)
        # self.CavalrymenNum.setGeometry(QtCore.QRect(w + 170, 585, 60, 15))
        # self.CavalrymenNum.setObjectName("CavalrymenNum")
        # self.TotalNum = QtWidgets.QLabel(self.centralwidget)
        # self.TotalNum.setGeometry(QtCore.QRect(w + 170, 620, 60, 15))
        # self.TotalNum.setObjectName("TotalNum")
        # self.WarriorsOffensive = QtWidgets.QLabel(self.centralwidget)
        # self.WarriorsOffensive.setGeometry(QtCore.QRect(w + 240, 480, 60, 15))
        # self.WarriorsOffensive.setObjectName("WarriorsOffensive")
        # self.ArchersOffensive = QtWidgets.QLabel(self.centralwidget)
        # self.ArchersOffensive.setGeometry(QtCore.QRect(w + 240, 515, 60, 15))
        # self.ArchersOffensive.setObjectName("ArchersOffensive")
        # self.CatapultsOffensive = QtWidgets.QLabel(self.centralwidget)
        # self.CatapultsOffensive.setGeometry(QtCore.QRect(w + 240, 550, 60, 15))
        # self.CatapultsOffensive.setObjectName("CatapultsOffensive")
        # self.CavalrymenOffensive = QtWidgets.QLabel(self.centralwidget)
        # self.CavalrymenOffensive.setGeometry(QtCore.QRect(w + 240, 585, 60, 15))
        # self.CavalrymenOffensive.setObjectName("CavalrymenOffensive")
        # self.TotalOffensive = QtWidgets.QLabel(self.centralwidget)
        # self.TotalOffensive.setGeometry(QtCore.QRect(w + 240, 620, 60, 15))
        # self.TotalOffensive.setObjectName("TotalOffensive")
        # self.WarriorsDefensive = QtWidgets.QLabel(self.centralwidget)
        # self.WarriorsDefensive.setGeometry(QtCore.QRect(w + 320, 480, 60, 15))
        # self.WarriorsDefensive.setObjectName("WarriorsDefensive")
        # self.ArchersDefensive = QtWidgets.QLabel(self.centralwidget)
        # self.ArchersDefensive.setGeometry(QtCore.QRect(w + 320, 515, 60, 15))
        # self.ArchersDefensive.setObjectName("ArchersDefensive")
        # self.CatapultsDefensive = QtWidgets.QLabel(self.centralwidget)
        # self.CatapultsDefensive.setGeometry(QtCore.QRect(w + 320, 550, 60, 15))
        # self.CatapultsDefensive.setObjectName("CatapultsDefensive")
        # self.CavalrymenDefensive = QtWidgets.QLabel(self.centralwidget)
        # self.CavalrymenDefensive.setGeometry(QtCore.QRect(w + 320, 585, 60, 15))
        # self.CavalrymenDefensive.setObjectName("CavalrymenDefensive")
        # self.TotalDefensive = QtWidgets.QLabel(self.centralwidget)
        # self.TotalDefensive.setGeometry(QtCore.QRect(w + 320, 620, 60, 15))
        # self.TotalDefensive.setObjectName("TotalDefensive")
        # self.CavalrymenIcon = QtWidgets.QLabel(self.centralwidget)
        # self.CavalrymenIcon.setGeometry(QtCore.QRect(w + 20, 575, 35, 35))
        # self.CavalrymenIcon.setText("")
        # self.CavalrymenIcon.setPixmap(QtGui.QPixmap("ui_icons/Horseman_icon_%28Civ6%29.png"))
        # self.CavalrymenIcon.setScaledContents(True)
        # self.CavalrymenIcon.setObjectName("CavalrymenIcon")
        # self.CatapultsIcon = QtWidgets.QLabel(self.centralwidget)
        # self.CatapultsIcon.setGeometry(QtCore.QRect(w + 20, 540, 35, 35))
        # self.CatapultsIcon.setText("")
        # self.CatapultsIcon.setPixmap(QtGui.QPixmap("ui_icons/Catapult_icon_%28Civ6%29.png"))
        # self.CatapultsIcon.setScaledContents(True)
        # self.CatapultsIcon.setObjectName("CatapultsIcon")
        # self.ArchersIcon = QtWidgets.QLabel(self.centralwidget)
        # self.ArchersIcon.setGeometry(QtCore.QRect(w + 20, 505, 35, 35))
        # self.ArchersIcon.setText("")
        # self.ArchersIcon.setPixmap(QtGui.QPixmap("ui_icons/Archer_icon_%28Civ6%29.png"))
        # self.ArchersIcon.setScaledContents(True)
        # self.ArchersIcon.setObjectName("ArchersIcon")
        # self.WarriorsIcon = QtWidgets.QLabel(self.centralwidget)
        # self.WarriorsIcon.setGeometry(QtCore.QRect(w + 20, 470, 35, 35))
        # self.WarriorsIcon.setText("")
        # self.WarriorsIcon.setPixmap(QtGui.QPixmap("ui_icons/Warrior_icon_%28Civ6%29.png"))
        # self.WarriorsIcon.setScaledContents(True)
        # self.WarriorsIcon.setObjectName("WarriorsIcon")
        # self.SawmillIcon = QtWidgets.QLabel(self.centralwidget)
        # self.SawmillIcon.setGeometry(QtCore.QRect(w + 10, 225, 35, 35))
        # self.SawmillIcon.setText("")
        # self.SawmillIcon.setPixmap(QtGui.QPixmap("ui_icons/Lumber_Mill_%28Civ6%29.png"))
        # self.SawmillIcon.setScaledContents(True)
        # self.SawmillIcon.setObjectName("SawmillIcon")
        # self.Sawmill = QtWidgets.QLabel(self.centralwidget)
        # self.Sawmill.setGeometry(QtCore.QRect(w + 70, 235, 60, 15))
        # self.Sawmill.setObjectName("Sawmill")
        # self.SawmilLevel = QtWidgets.QLabel(self.centralwidget)
        # self.SawmilLevel.setGeometry(QtCore.QRect(w + 170, 235, 60, 15))
        # self.SawmilLevel.setObjectName("SawmilLevel")
        # self.SawmillNextLevel = QtWidgets.QLabel(self.centralwidget)
        # self.SawmillNextLevel.setGeometry(QtCore.QRect(w + 280, 235, 75, 15))
        # self.SawmillNextLevel.setObjectName("SawmillNextLevel")
        # self.VillageCapacity = QtWidgets.QLabel(self.centralwidget)
        # self.VillageCapacity.setGeometry(QtCore.QRect(w + 60, 420, 80, 15))
        # self.VillageCapacity.setObjectName("VillageCapacity")
        # self.VillageCapacityValue = QtWidgets.QLabel(self.centralwidget)
        # self.VillageCapacityValue.setGeometry(QtCore.QRect(w + 170, 420, 50, 15))
        # self.VillageCapacityValue.setObjectName("VillageCapacityValue")
        # self.SpiesValue = QtWidgets.QLabel(self.centralwidget)
        # self.SpiesValue.setGeometry(QtCore.QRect(w + 320, 420, 50, 15))
        # self.SpiesValue.setObjectName("SpiesValue")
        # self.Spies = QtWidgets.QLabel(self.centralwidget)
        # self.Spies.setGeometry(QtCore.QRect(w + 280, 420, 80, 15))
        # self.Spies.setObjectName("Spies")
        # self.SpiesIcon = QtWidgets.QLabel(self.centralwidget)
        # self.SpiesIcon.setGeometry(QtCore.QRect(w + 240, 410, 35, 35))
        # self.SpiesIcon.setText("")
        # self.SpiesIcon.setPixmap(QtGui.QPixmap("ui_icons/Spy_icon_%28Civ6%29.png"))
        # self.SpiesIcon.setScaledContents(True)
        # self.SpiesIcon.setObjectName("SpiesIcon")
        # self.QuarryIcon = QtWidgets.QLabel(self.centralwidget)
        # self.QuarryIcon.setGeometry(QtCore.QRect(w + 10, 190, 35, 35))
        # self.QuarryIcon.setText("")
        # self.QuarryIcon.setPixmap(QtGui.QPixmap("ui_icons/Quarry_%28Civ6%29.png"))
        # self.QuarryIcon.setScaledContents(True)
        # self.QuarryIcon.setObjectName("QuarryIcon")
        # self.Quarry = QtWidgets.QLabel(self.centralwidget)
        # self.Quarry.setGeometry(QtCore.QRect(w + 70, 200, 60, 15))
        # self.Quarry.setObjectName("Quarry")
        # self.QuarryLevel = QtWidgets.QLabel(self.centralwidget)
        # self.QuarryLevel.setGeometry(QtCore.QRect(w + 170, 200, 60, 15))
        # self.QuarryLevel.setObjectName("QuarryLevel")
        # self.QuarryNextLevel = QtWidgets.QLabel(self.centralwidget)
        # self.QuarryNextLevel.setGeometry(QtCore.QRect(w + 280, 200, 75, 15))
        # self.QuarryNextLevel.setObjectName("QuarryNextLevel")
        # self.WallIcon = QtWidgets.QLabel(self.centralwidget)
        # self.WallIcon.setGeometry(QtCore.QRect(w + 10, 260, 35, 35))
        # self.WallIcon.setText("")
        # self.WallIcon.setPixmap(QtGui.QPixmap("ui_icons/Great_Wall_%28Civ6%29.png"))
        # self.WallIcon.setScaledContents(True)
        # self.WallIcon.setObjectName("WallIcon")
        # self.WarehouseIcon = QtWidgets.QLabel(self.centralwidget)
        # self.WarehouseIcon.setGeometry(QtCore.QRect(w + 10, 295, 35, 35))
        # self.WarehouseIcon.setText("")
        # self.WarehouseIcon.setPixmap(QtGui.QPixmap("ui_icons/Feitoria_%28Civ6%29.png"))
        # self.WarehouseIcon.setScaledContents(True)
        # self.WarehouseIcon.setObjectName("WarehouseIcon")
        # self.Wall = QtWidgets.QLabel(self.centralwidget)
        # self.Wall.setGeometry(QtCore.QRect(w + 70, 270, 60, 15))
        # self.Wall.setObjectName("Wall")
        # self.Warehouse = QtWidgets.QLabel(self.centralwidget)
        # self.Warehouse.setGeometry(QtCore.QRect(w + 70, 305, 60, 15))
        # self.Warehouse.setObjectName("Warehouse")
        # self.WallLevel = QtWidgets.QLabel(self.centralwidget)
        # self.WallLevel.setGeometry(QtCore.QRect(w + 170, 270, 60, 15))
        # self.WallLevel.setObjectName("WallLevel")
        # self.WarehouseLevel = QtWidgets.QLabel(self.centralwidget)
        # self.WarehouseLevel.setGeometry(QtCore.QRect(w + 170, 305, 60, 15))
        # self.WarehouseLevel.setObjectName("WarehouseLevel")
        # self.WallNextLevel = QtWidgets.QLabel(self.centralwidget)
        # self.WallNextLevel.setGeometry(QtCore.QRect(w + 280, 270, 75, 15))
        # self.WallNextLevel.setObjectName("WallNextLevel")
        # self.WarehouseNextLevel = QtWidgets.QLabel(self.centralwidget)
        # self.WarehouseNextLevel.setGeometry(QtCore.QRect(w + 280, 305, 75, 15))
        # self.WarehouseNextLevel.setObjectName("WarehouseNextLevel")
